name: tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

defaults:
  run:
    working-directory: .

jobs:
  test_on_linux:
    name: Run E2E tests on Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: npm i
      - name: Build
        run: npx hardhat compile
      - name: Run tests
        run: npx hardhat test
